# Generated by Django 3.0.dev20190501095127 on 2019-05-10 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_auto_20190510_1511'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='age',
            field=models.IntegerField(default=20),
        ),
        migrations.AddField(
            model_name='job',
            name='educationType',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='job',
            name='lengthOfService',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='job',
            name='placeOfResidence',
            field=models.CharField(default='', max_length=200),
        ),
    ]
